### ISSUE TITLE
Alice model dev data

### ISSUE THREAD

**Issue by nweir127** [sorami/Membership-Inference-Attacks-on-Sequence-to-Sequence-Models#1]
I would like to replicate the training of the Alice model. Would it be possible for you to release either the BPE-tokenized `newstest2017` data or the model used to tokenize it?

Thanks

**Comment by mjpost** [comment]
Hi—Here is the preprocessing pipeline (run `pre.sh`):

* http://cs.jhu.edu/~post/tmp/alice-de-en-preproc.tgz
* http://cs.jhu.edu/~post/tmp/alice-en-de-preproc.tgz

Let me know if you need anything else!
